export const regions = [
  {
    id: "south-ethiopia",
    name: "South Ethiopia",
    description:
      "Highland watersheds, agroforestry corridors, and pressure zones near expanding settlements.",
    signal: "Strong soil and water recovery potential",
    stats: {
      watersheds: 18,
      forestLoss: "14.2k ha",
      households: "286k",
    },
  },
  {
    id: "southwest-ethiopia",
    name: "Southwest Ethiopia",
    description:
      "Moist forest landscapes with high biodiversity value, coffee systems, and carbon-rich restoration edges.",
    signal: "Highest biodiversity and carbon co-benefits",
    stats: {
      watersheds: 22,
      forestLoss: "19.8k ha",
      households: "341k",
    },
  },
];

export const layers = [
  {
    id: "land-cover",
    name: "Land cover",
    source: "ESA WorldCover",
    description: "Detects degraded cropland, grassland, woodland, and settlement edges.",
  },
  {
    id: "forest-loss",
    name: "Forest loss",
    source: "Global Forest Watch / UMD",
    description: "Weights recent tree cover loss and fragmentation near priority habitat.",
  },
  {
    id: "rainfall",
    name: "Rainfall",
    source: "CHIRPS",
    description: "Highlights rainfall stability and climate suitability for restoration.",
  },
  {
    id: "soil-quality",
    name: "Soil quality",
    source: "SoilGrids / ISRIC + SRTM DEM",
    description: "Scores erosion risk, organic matter proxy, and slope sensitivity.",
  },
  {
    id: "carbon-potential",
    name: "Carbon potential",
    source: "WRI restoration maps + GFW",
    description: "Estimates above-ground biomass recovery and sequestration upside.",
  },
  {
    id: "water-availability",
    name: "Water availability",
    source: "CHIRPS + SoilGrids + SRTM",
    description: "Prioritizes watersheds where vegetation recovery improves flows.",
  },
  {
    id: "population-pressure",
    name: "Population pressure",
    source: "WorldPop, GHSL, OSM/HOTOSM",
    description: "Balances restoration feasibility with livelihood pressure and demand.",
  },
  {
    id: "biodiversity-potential",
    name: "Biodiversity potential",
    source: "WDPA + CIFOR-ICRAF species atlas",
    description: "Identifies corridors, endemic species value, and habitat connectivity.",
  },
];

export const dataSources = [
  {
    theme: "Admin boundaries",
    source: "HDX/OCHA Ethiopia Admin 0-3",
    use: "Filter Admin 1 to South Ethiopia and Southwest Ethiopia; aggregate by zone and woreda.",
  },
  {
    theme: "Restoration context",
    source: "Ethiopia Tree-Based Landscape Restoration Atlas / MEFCC-WRI",
    use: "Crosswalk older SNNPR-era restoration priorities to current boundaries.",
  },
  {
    theme: "Satellite imagery",
    source: "Sentinel-2, Sentinel-1 SAR, Landsat Collection 2",
    use: "Vegetation, moisture, degradation, and historical land-cover change screening.",
  },
  {
    theme: "Land and forest",
    source: "ESA WorldCover + Global Forest Watch / UMD",
    use: "Land-use masking, tree-cover loss, canopy change, and regeneration opportunity.",
  },
  {
    theme: "Climate, terrain, soils",
    source: "CHIRPS, SRTM DEM, SoilGrids / ISRIC",
    use: "Rainfall reliability, slope, erosion risk, soil carbon, pH, and texture.",
  },
  {
    theme: "Safeguards and species",
    source: "WDPA, WorldPop, GHSL, OSM/HOTOSM, CIFOR-ICRAF",
    use: "Protected areas, population pressure, access, social risk, and tree species suitability.",
  },
];

export const restorationAreas = [
  {
    id: "chebera-churchura-buffer",
    regionId: "south-ethiopia",
    name: "Chebera-Churchura Buffer Landscape",
    zone: "Dawuro / Konta",
    rank: 1,
    score: 91,
    confidence: "High",
    hectares: "42,800 ha",
    households: "38,400",
    intervention: "Assisted natural regeneration with riparian buffers",
    timeline: "24 month pilot",
    investment: "$2.4M",
    tags: ["Wildlife corridor", "Watershed", "Community forest"],
    scores: {
      biodiversity: 94,
      carbon: 88,
      water: 92,
      soil: 85,
      livelihoods: 89,
      forestLoss: 83,
    },
    rationale: [
      "Connects degraded woodland patches around a protected-area buffer where habitat continuity is recoverable.",
      "Restoration along stream corridors can reduce sediment load and stabilize dry-season water access.",
      "Community forestry groups and honey cooperatives create a practical livelihood pathway for maintenance.",
    ],
    risks: ["Human-wildlife conflict near farms", "Need clear benefit-sharing agreements"],
    outputs: ["8,600 ha ANR", "260 km riparian buffer", "1,900 jobs in nursery and monitoring"],
  },
  {
    id: "basketo-slope-mosaic",
    regionId: "south-ethiopia",
    name: "Basketo Slope Mosaic",
    zone: "Basketo Special Woreda",
    rank: 2,
    score: 86,
    confidence: "Medium-high",
    hectares: "31,200 ha",
    households: "27,100",
    intervention: "Agroforestry enrichment and erosion-control planting",
    timeline: "18 month pilot",
    investment: "$1.8M",
    tags: ["Erosion control", "Agroforestry", "Food security"],
    scores: {
      biodiversity: 78,
      carbon: 81,
      water: 84,
      soil: 93,
      livelihoods: 90,
      forestLoss: 79,
    },
    rationale: [
      "Steep cultivated slopes show strong soil recovery upside with contour planting and perennial cover.",
      "Household benefit is high because shade trees, fruit trees, and fodder species can be integrated into farms.",
      "Rainfall reliability supports fast establishment if nurseries are launched before the wet season.",
    ],
    risks: ["Seedling survival depends on early farmer incentives", "Fragmented parcels require local coordination"],
    outputs: ["14,000 agroforestry plots", "95 community nurseries", "34% erosion-risk reduction"],
  },
  {
    id: "gamo-highland-springs",
    regionId: "south-ethiopia",
    name: "Gamo Highland Springs",
    zone: "Gamo Highlands",
    rank: 3,
    score: 82,
    confidence: "Medium",
    hectares: "24,600 ha",
    households: "21,800",
    intervention: "Spring protection, exclosures, and native highland species",
    timeline: "12 month pilot",
    investment: "$1.3M",
    tags: ["Springs", "Highland forest", "Soil moisture"],
    scores: {
      biodiversity: 75,
      carbon: 76,
      water: 91,
      soil: 87,
      livelihoods: 82,
      forestLoss: 72,
    },
    rationale: [
      "Water availability signals are high around spring recharge zones used by dense rural communities.",
      "Small exclosures can protect regeneration while preserving access through negotiated grass-cutting rules.",
      "Native highland species improve slope stability and reduce pressure on remnant forest patches.",
    ],
    risks: ["Grazing pressure may reduce regeneration", "Needs local water committee enforcement"],
    outputs: ["120 protected springs", "4,200 ha exclosures", "68 local water committees"],
  },
  {
    id: "maji-bench-forest-edge",
    regionId: "southwest-ethiopia",
    name: "Maji-Bench Forest Edge",
    zone: "Bench Sheko / West Omo",
    rank: 1,
    score: 94,
    confidence: "High",
    hectares: "56,900 ha",
    households: "44,700",
    intervention: "Forest-edge regeneration and coffee shade restoration",
    timeline: "30 month pilot",
    investment: "$3.1M",
    tags: ["Carbon", "Coffee shade", "Biodiversity corridor"],
    scores: {
      biodiversity: 96,
      carbon: 95,
      water: 88,
      soil: 84,
      livelihoods: 91,
      forestLoss: 89,
    },
    rationale: [
      "High carbon potential overlaps with biodiversity corridors and active forest-edge degradation.",
      "Shade coffee restoration can protect livelihoods while reducing conversion pressure.",
      "Landscape has enough contiguous habitat to create measurable connectivity gains within two seasons.",
    ],
    risks: ["Commodity price volatility affects adoption", "Boundary mapping must be validated locally"],
    outputs: ["18,500 ha forest-edge ANR", "12,000 shade coffee plots", "410 ktCO2e projected by year 10"],
  },
  {
    id: "kafa-biosphere-corridor",
    regionId: "southwest-ethiopia",
    name: "Kafa Biosphere Corridor",
    zone: "Kafa",
    rank: 2,
    score: 90,
    confidence: "High",
    hectares: "48,300 ha",
    households: "32,900",
    intervention: "Biodiversity corridor restoration with community forest enterprises",
    timeline: "24 month pilot",
    investment: "$2.7M",
    tags: ["Biosphere", "Endemism", "Community enterprise"],
    scores: {
      biodiversity: 98,
      carbon: 86,
      water: 86,
      soil: 80,
      livelihoods: 85,
      forestLoss: 82,
    },
    rationale: [
      "Biodiversity potential is the strongest signal, with restoration closing gaps between forest fragments.",
      "Existing community enterprises can support monitoring and generate income from non-timber products.",
      "Moderate forest-loss pressure means intervention can prevent expensive future degradation.",
    ],
    risks: ["Corridor alignment needs participatory mapping", "Benefits accrue slowly without enterprise support"],
    outputs: ["9 corridor blocks", "6,800 ha enrichment planting", "52 enterprise groups supported"],
  },
  {
    id: "sheka-wet-forest-buffer",
    regionId: "southwest-ethiopia",
    name: "Sheka Wet Forest Buffer",
    zone: "Sheka",
    rank: 3,
    score: 87,
    confidence: "Medium-high",
    hectares: "35,700 ha",
    households: "25,600",
    intervention: "Wet forest buffer protection and watershed restoration",
    timeline: "18 month pilot",
    investment: "$2.0M",
    tags: ["Wet forest", "Water security", "Buffer zone"],
    scores: {
      biodiversity: 92,
      carbon: 84,
      water: 90,
      soil: 79,
      livelihoods: 80,
      forestLoss: 77,
    },
    rationale: [
      "Wet forest buffers protect water regulation services for downstream communities.",
      "Restoration is suitable where land cover is degraded but natural regeneration sources remain nearby.",
      "Priority is driven by combined water and biodiversity benefits rather than single-metric carbon gains.",
    ],
    risks: ["Access constraints in wet season", "Monitoring costs higher in remote forest blocks"],
    outputs: ["7,400 ha buffer recovery", "38 watershed patrol teams", "210 km streambank stabilization"],
  },
];

export const portfolioMetrics = {
  estimatedCarbon: "1.86 MtCO2e",
  waterBenefit: "710k people",
  livelihoodReach: "190k households",
  restorationPotential: "239k ha",
};
